# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0002_auto_20180331_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkdetails',
            name='checked_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 20, 50, 7, 160880)),
        ),
    ]
