# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0002_auto_20180331_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkdetails',
            name='checked_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 23, 47, 45, 454559)),
        ),
    ]
