# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onroad', '0003_auto_20180331_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkdetails',
            name='checked_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 21, 53, 28, 300171)),
        ),
    ]
