# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 17:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_type', models.IntegerField(blank=True, choices=[(1, 'Road Officer'), (2, 'SP'), (0, 'Driver')], null=True)),
                ('aadhar_id', models.CharField(default=0, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('fine', models.IntegerField(default=0)),
                ('fine_date', models.DateTimeField(default=datetime.datetime(2018, 3, 31, 22, 59, 57, 944548))),
                ('base_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensenum', models.CharField(default=0, max_length=100)),
                ('helmetid', models.IntegerField(blank=True, default=0, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vehicledetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=10, unique=True)),
                ('insuranceid', models.CharField(blank=True, max_length=50, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
