# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 17:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fine_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 23, 4, 21, 982591)),
        ),
    ]
