# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 19:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleusers', '0002_user_fine_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fine_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 0, 35, 57, 580636)),
        ),
    ]
