# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-30 19:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleusers', '0003_auto_20180331_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fine_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 1, 15, 18, 265483)),
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='regno',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
