# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleusers', '0004_auto_20180331_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fine_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 20, 50, 7, 156881)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Road Officer'), (1, 'SP'), (0, 'Driver')], null=True),
        ),
    ]
