# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-31 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicleusers', '0005_auto_20180331_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fine_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 31, 21, 53, 28, 295660)),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Road Officer'), (2, 'SP'), (0, 'Driver')], null=True),
        ),
    ]
